### ISSUE TITLE
Support for pytorch >1.0 and CUDA10.

### ISSUE THREAD

**Issue by juanmed** [mileyan/AnyNet#10]
Hello,

Thanks for sharing your code and and paper on the impressive results achieved on jetson tx2. I wanted to replicate your results but now I am facing difficulties installing all the dependencies on a jetson nano. There are two issues:

a) Pytorch deprecation of extensions as stated in #4 
b) I have been unable to install (or compile from source and install) pytorch0.4 on jetson nano (ubuntu18.04, CUDA10)

So I was wondering if you could please provide some pointers on how to add suport for pytorch v1.0 more specifically for the `spn` folder of scripts (I undestand one has to use cpp_extensions and rewrite some parts of the code), and/or if you could provide any directions on installing pytorch 0.4 on ubuntu18.04 with CUDA10.

Thank you very much!

**Comment by mileyan** [comment]
Hi,
Now our code is support pytorch 1.0 and cuda 10. Please check it.
