### ISSUE TITLE
An Error in Pytorch1.4.0

### ISSUE THREAD

**Issue by yanqswhu** [mileyan/AnyNet#17]
Code ( main.py line 124 ):
` outputs = [torch.squeeze(output, 1) for output in outputs]`

The shape of outputs and disp_L  are [6,1,*,*]，so it seems unnecessary to squeeze.

**Comment by mileyan** [comment]
Hi, now it only supports pytorch 1.0. Please try pytorch 1.0. I am working on adapting the code to pytorch 1.4.

**Comment by jankais3r** [comment]
Hi, is there still a plan to support pytorch 1.4?
