### ISSUE TITLE
A question about spn

### ISSUE THREAD

**Issue by walkingmelon** [mileyan/AnyNet#4]
Dear @mileyan , when I used spn（sh make.sh）, there was an error(ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead) and I didn't know how to solve it. 
My Computer Environment： python-3.5  CUDA-9.0.176   pytorch-0.4.
Looking forward to your reply！

**Comment by mileyan** [comment]
Can you try CUDA-8.0? It might have some problems for CUDA-9.0 now. I will try to fix it. But CUDA-8.0 should be work.
