### ISSUE TITLE
error when compiling spn

### ISSUE THREAD

**Issue by 1tac11** [mileyan/AnyNet#42]
hi @mileyan,

when compiling the spn-model in `models/spn` I get this error:

> Compiling gaterecurrent2dnoind layer kernels by nvcc...
> python: can't open file 'setup.py': [Errno 2] No such file or directory

`cat make.sh` reveals that `python setup.py`is called in the same directory, but there is no file setup.py. What am I doing wrong here?

My system:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Thu_Jun_11_22:26:38_PDT_2020
Cuda compilation tools, release 11.0, V11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0
NVIDIA-SMI 450.51.05    Driver Version: 450.51.05    CUDA Version: 11.0

Thank you in advance

**Comment by weipeng0703** [comment]
> 
Hello, I encounter the same problem, I could not find the `setup.py` file, how did you solve it

**Comment by weipeng0703** [comment]
Hello @1seck , I encounter the same problem, I could not find the setup.py file, how did you solve the problem? Thank you

**Comment by weipeng0703** [comment]
Hello @1seck , I encounter the same problem, I could not find the `setup.py`, how did you solve the problem? Thank you

**Comment by flyxuexi** [comment]
hi，Could you tell me how to solve this problem? I found setup.py in spn_t1
